## Importação de bases e tratamento de dados:

In [41]:
import pandas as pd

arquivo_bps = 'export-BPS.csv'
arquivo_cinema = 'export-CINEMA.csv'

df_bps = pd.read_csv(arquivo_bps)
df_cinema = pd.read_csv(arquivo_cinema)

display(df_bps.head())
display(df_cinema.head())

,Código,Item de Estoque,Descrição Grupo,Compõe Produto,Unidade,Fichas,Quantidade,Custo Médio,Subtotal/C.M.
0,2,CAPPUCCINO SCADA - 1KG,CAFES / BASES EM PO,True,KG,0,"12,6940","83,8400","1.064,2650"
1,6,CAPPUCCINO DIET,CAFES / BASES EM PO,True,KG,0,"0,6720","239,4857","160,9344"
2,107,CHA QUENTE NACIONAL SACHE,CAFES / BASES EM PO,True,UN,0,"198,0000","0,3990","79,0020"
3,441,"CHOCOLATE CREMOSO- 1,05KG",CAFES / BASES EM PO,True,KG,0,"6,7290","105,0667","706,9938"
4,662,SCADA BLEND GRAO 250G,CAFES / BASES EM PO,True,KG,0,"6,1790","108,0000","667,3320"

,Código,Item de Estoque,Descrição Grupo,Compõe Produto,Unidade,Fichas,Quantidade,Custo Médio,Subtotal/C.M.
0,2,CAPPUCCINO SCADA - 1KG,CAFES / BASES EM PO,True,KG,0,"6,7500","83,8400","565,9200"
1,6,CAPPUCCINO DIET,CAFES / BASES EM PO,True,KG,0,"0,1190","239,4857","28,4988"
2,107,CHA QUENTE NACIONAL SACHE,CAFES / BASES EM PO,True,UN,0,"142,0000","1,0890","154,6380"
3,441,"CHOCOLATE CREMOSO- 1,05KG",CAFES / BASES EM PO,True,KG,0,"5,0000","105,0667","525,3335"
4,662,SCADA BLEND GRAO 250G,CAFES / BASES EM PO,True,KG,0,"2,5500","108,0000","275,4000"

In [42]:
# Agrupamento das bases:
comparativo_custos = pd.merge(
    df_bps[['Código', 'Item de Estoque', 'Descrição Grupo', 'Unidade', 'Custo Médio']],
    df_cinema[['Código', 'Custo Médio']],
    on='Código',
    suffixes=('_BPS', '_CINEMA'),
    how='outer'
)

# Corrigir pontuação das colunas de Custo, alterando a "," por ".":
comparativo_custos["Custo Médio_BPS"] = comparativo_custos["Custo Médio_BPS"].str.replace(",", ".")
comparativo_custos["Custo Médio_CINEMA"] = comparativo_custos["Custo Médio_CINEMA"].str.replace(",", ".")
# Transformar colunas de Custo Médio em numéricas:
comparativo_custos['Custo Médio_BPS'] = pd.to_numeric(comparativo_custos['Custo Médio_BPS'], errors='coerce')
comparativo_custos['Custo Médio_CINEMA'] = pd.to_numeric(comparativo_custos['Custo Médio_CINEMA'], errors='coerce')

display(comparativo_custos)
comparativo_custos.info()

,Código,Item de Estoque,Descrição Grupo,Unidade,Custo Médio_BPS,Custo Médio_CINEMA
0,2,CAPPUCCINO SCADA - 1KG,CAFES / BASES EM PO,KG,83.8400,83.8400
1,4,LEITE INTEGRAL,LATICINIOS / FRIOS,LT,5.7200,5.8600
2,5,CHANTILY,LATICINIOS / FRIOS,LT,19.9952,21.8000
3,6,CAPPUCCINO DIET,CAFES / BASES EM PO,KG,239.4857,239.4857
4,9,CALDA CHOCOLATE,SECOS,KG,25.8889,57.1429
...,...,...,...,...,...,...
374,1313,GELEIA DE CAFÉ DANEGA,DOCES,KG,0.0000,0.0000
375,1314,GELEIA DE CAFÉ C/ PIMENTA DANEGA,DOCES,KG,0.0000,0.0000
376,1315,GELEIA ZERO AÇUCAR DANEGA,DOCES,KG,0.0000,0.0000
377,1316,BRIGADEIRO PISTACHE ZERO,DOCES,UN,0.0000,NaN
378,1317,BRIGADEIRO CHURROS ZERO,DOCES,UN,0.0000,0.0000

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 379 entries, 0 to 378
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Código              379 non-null    int64
 1   Item de Estoque     331 non-null    object
 2   Descrição Grupo     331 non-null    object
 3   Unidade             331 non-null    object
 4   Custo Médio_BPS     329 non-null    float64
 5   Custo Médio_CINEMA  329 non-null    float64
dtypes: float64(2), int64(1), object(3)
memory usage: 17.9+ KB

## Desenvolvimento e Análises:

In [43]:
# Inserir coluna comparativa de custos:
comparativo_custos['Diferença de Custo'] = comparativo_custos['Custo Médio_CINEMA'] - comparativo_custos['Custo Médio_BPS']
display(comparativo_custos)

,Código,Item de Estoque,Descrição Grupo,Unidade,Custo Médio_BPS,Custo Médio_CINEMA,Diferença de Custo
0,2,CAPPUCCINO SCADA - 1KG,CAFES / BASES EM PO,KG,83.8400,83.8400,0.0000
1,4,LEITE INTEGRAL,LATICINIOS / FRIOS,LT,5.7200,5.8600,0.1400
2,5,CHANTILY,LATICINIOS / FRIOS,LT,19.9952,21.8000,1.8048
3,6,CAPPUCCINO DIET,CAFES / BASES EM PO,KG,239.4857,239.4857,0.0000
4,9,CALDA CHOCOLATE,SECOS,KG,25.8889,57.1429,31.2540
...,...,...,...,...,...,...,...
374,1313,GELEIA DE CAFÉ DANEGA,DOCES,KG,0.0000,0.0000,0.0000
375,1314,GELEIA DE CAFÉ C/ PIMENTA DANEGA,DOCES,KG,0.0000,0.0000,0.0000
376,1315,GELEIA ZERO AÇUCAR DANEGA,DOCES,KG,0.0000,0.0000,0.0000
377,1316,BRIGADEIRO PISTACHE ZERO,DOCES,UN,0.0000,NaN,NaN
378,1317,BRIGADEIRO CHURROS ZERO,DOCES,UN,0.0000,0.0000,0.0000

In [44]:
# Inserir coluna de Status de Comparação:
import numpy as np

comparativo_custos["Status"] = np.where(
    comparativo_custos["Diferença de Custo"] > 0, "MAIOR",
    np.where(comparativo_custos["Diferença de Custo"] < 0, "MENOR", "-")
)

display(comparativo_custos)

,Código,Item de Estoque,Descrição Grupo,Unidade,Custo Médio_BPS,Custo Médio_CINEMA,Diferença de Custo,Status
0,2,CAPPUCCINO SCADA - 1KG,CAFES / BASES EM PO,KG,83.8400,83.8400,0.0000,-
1,4,LEITE INTEGRAL,LATICINIOS / FRIOS,LT,5.7200,5.8600,0.1400,MAIOR
2,5,CHANTILY,LATICINIOS / FRIOS,LT,19.9952,21.8000,1.8048,MAIOR
3,6,CAPPUCCINO DIET,CAFES / BASES EM PO,KG,239.4857,239.4857,0.0000,-
4,9,CALDA CHOCOLATE,SECOS,KG,25.8889,57.1429,31.2540,MAIOR
...,...,...,...,...,...,...,...,...
374,1313,GELEIA DE CAFÉ DANEGA,DOCES,KG,0.0000,0.0000,0.0000,-
375,1314,GELEIA DE CAFÉ C/ PIMENTA DANEGA,DOCES,KG,0.0000,0.0000,0.0000,-
376,1315,GELEIA ZERO AÇUCAR DANEGA,DOCES,KG,0.0000,0.0000,0.0000,-
377,1316,BRIGADEIRO PISTACHE ZERO,DOCES,UN,0.0000,NaN,NaN,-
378,1317,BRIGADEIRO CHURROS ZERO,DOCES,UN,0.0000,0.0000,0.0000,-

In [ ]:
# Exportar DF em formato XLSX:
#comparativo_custos.to_excel("comparativo_custo_estoque.xlsx", index=False)